name: Rutilea
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11.0
  - pip==23.3 
  - numpy==1.26.0
  - pillow==10.0.1
  - pytorch==2.0.1
  - transformers==4.32.1
  - langchain==0.0.320
  - openai==0.27.4
  # - huggingface_hub==0.18.0   # Only used in `experiments`
  - spotipy==2.23.0
  - tk==8.6.13
  - pip:
    - customtkinter==5.2.1