name: Rutilea
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pillow
  - langchain
  - pytorch
  - transformers
  - openai  # for ChatOpenAI
  - huggingface_hub   # Only used in `experiments`
  - spotipy
  - tkinter
  - pip:
    - customtkinter