name: Rutilea
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - pillow
  - pytorch
  - transformers
  - langchain
  - openai
  - huggingface_hub   # Only used in `experiments`
  - spotipy
  - tk
  - pip:
    - customtkinter